### ISSUE TITLE
encoding problem?

### ISSUE THREAD

**Issue by jkister** [jttyeung/smile-more-donate-more#6]
seems there is some sort of encoding problem, with the addon many urls get mangled.

for example, clicking any link from https://www.dealnews.com/s313/Amazon/ 

shows an error like: http://i.imgur.com/iGOtOaF.png

disabling the addon makes the links (from dealnews) clickable.

FF 55.0.3

**Comment by jttyeung** [comment]
@jkister This is fixed in v1.4 of the extension - thank you for reporting.
